### ISSUE TITLE
Cannot POST /hosted/pay/undefined after submiting card or phone number

### ISSUE THREAD

**Issue by Mowzey123** [Jake-parkers/ionic-rave#8]
Hello,
I have followed all the instructions here on how to integrate rave API in ionic which seems to run fine.
The payment modal pops up fine and I am able to add a card or mobile number.

On submitting the request redirects to this here

 https://ravemodal-dev.herokuapp.com/hosted/pay/undefined?flwref=FLW-MOCK-e45deb3ca2053f0f55182f87747452e5&txref=kcmtj

and the response is:
 Cannot POST /hosted/pay/undefined

**Comment by Mowzey123** [comment]
From rave dashboard support team,
You need to add redirect_url  when initializing the rave modal.
I think it was missed here

**Comment by elvisokohasirifi** [comment]
I have the same issue. I have inserted my callback URL but it is still not working
